micronaut:
  application:
    name: nossaCasaDoCodigo

datasources:
  default:
      url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/cdc`}
      driverClassName: org.postgresql.Driver
      username: ${JDBC_USER:postgres}
      password: ${JDBC_PASSWORD:postgres}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
